-- include subprojects
includes("lib/commonlibsf")

-- set project constants
set_project("OSF UI")
set_version("2.0.0")
set_license("GPL-3.0")
set_languages("c++23")
set_warnings("allextra")

-- add common rules
add_rules("mode.debug", "mode.releasedbg")
add_rules("plugin.vsxmake.autoupdate")

-- JSON for config, view manifests, and the message bridge
add_requires("nlohmann_json")
add_requires("glaze")

-- Production host executable. Self-contained on purpose: static CRT + static
-- WebView2 loader, because it runs from a mirrored real path with no neighbours.
target("osfui-webview2-host")
        set_kind("binary")
        set_basename("osfui_webview2_host")
        set_default(false)
        set_languages("c++23")
        set_warnings("allextra")
        -- Interpret source (and encode narrow/wide literals) as UTF-8. Without
        -- /utf-8 MSVC decodes non-ASCII host log and UI literals as the system
        -- code page. Embedded scripts are compiled as generated byte arrays.
        set_encodings("utf-8")
        set_runtimes("MT")
        add_rules("mode.debug", "mode.releasedbg", "utils.bin2c")
        add_files("tools/webview2_host/**.cpp", "tools/webview2_shared/**.cpp")
        add_files("tools/webview2_host/scripts/**.js", { rule = "utils.bin2c" })
        add_headerfiles("tools/webview2_host/**.h", "tools/webview2_shared/**.h")
        add_includedirs("src", "tools/webview2_shared")
        add_packages("nlohmann_json", "glaze")
        add_syslinks(
            "d3d11", "dxgi", "windowsapp", "runtimeobject", "CoreMessaging",
            "ole32", "oleaut32", "uuid", "comsuppw", "taskschd", "advapi32",
            "user32", "shell32")
        add_ldflags("/SUBSYSTEM:WINDOWS", { force = true })
        add_cxflags("cl::/Zc:preprocessor", {force = true})
        on_load(function(target)
            local sdk = os.getenv("WEBVIEW2_SDK_DIR")
            if not sdk or sdk == "" then
                sdk = path.join(os.projectdir(), "external", "webview2")
            end
            local native = path.join(sdk, "build", "native")
            if not os.isfile(path.join(native, "include", "WebView2.h")) then
                raise("OSFUI WebView2 host: unpack Microsoft.Web.WebView2 into " ..
                    "external/webview2 or set WEBVIEW2_SDK_DIR to the NuGet package root")
            end
            target:add("includedirs", path.join(native, "include"))
            target:add("linkdirs", path.join(native, "x64"))
            target:add("links", "WebView2LoaderStatic")
        end)

-- Windows-only transport regression suite. Kept separate from tests/native/run.sh,
-- whose sources are intentionally portable and do not include Windows.h.
target("wv2-pipe-tests")
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_warnings("allextra")
    set_encodings("utf-8")
    add_files("tests/native/wv2_pipe_tests.cpp", "tools/webview2_shared/Wv2Pipe.cpp")
    add_includedirs("tools/webview2_shared", "tests/native/stubs")
    add_syslinks("advapi32")

-- Deployment-free tests for the renderer-independent v2 runtime state.
target("osfui-v2-tests")
    set_kind("binary")
    set_default(false)
    set_languages("c++23")
    set_warnings("allextra")
    set_encodings("utf-8")
    add_packages("glaze")
    add_cxflags("cl::/Zc:preprocessor", { force = true })
    add_files(
        "tests/v2/papyrus_tests.cpp",
        "tests/v2/runtime_tests.cpp",
        "tests/v2/web_view_presenter_tests.cpp",
        "src/v2/Presentation/WebViewPresenter.cpp",
        "src/v2/Runtime/ViewManifest.cpp",
        "src/v2/Runtime/ViewDiscovery.cpp",
        "src/v2/Runtime/ViewCatalog.cpp",
        "src/v2/Runtime/ViewPresentationController.cpp",
        "src/v2/Runtime/ViewRuntime.cpp",
        "src/v2/Runtime/RuntimeCoordinator.cpp",
        "src/v2/Scripts/Papyrus.cpp"
    )
    add_includedirs("tests/native/stubs", "src")
    set_pcxxheader("tests/native/stubs/pch.h")

-- define targets
-- target name == repo folder == MO2 mod folder (deploy goes to XSE_SF_MODS_PATH\<target name>)
target("OSF UI")
    -- DLL basename (target name has a space for the MO2 folder; the binary itself is the space-free "OSFUI.dll"). 
    -- Data folder is SFSE/Plugins/OSFUI/
    set_basename("OSFUI")
    -- Compile UTF-8 source with UTF-8 narrow/wide literals (see the host target
    -- note above); the commonlibsf subproject sets this for itself but it does
    -- not propagate to this target.
    set_encodings("utf-8")
    add_rules("commonlibsf.plugin", {
        name = "OSF UI",
        author = "ozooma10",
        description = "Web Interface Framework for Starfield",
        email = "ozooma10@users.noreply.github.com"
    })

    -- add packages
    add_packages("nlohmann_json", "glaze")

    -- D3D12 overlay compositor (composite/): the device/queue are the game's, but we still need these for our own root signature, pipeline state, and runtime shader compilation.
    -- d3dcompiler is used to build the overlay shaders at runtime
    -- shell32/ole32: SHGetKnownFolderPath for the writable settings path.
    add_syslinks("d3d12", "dxgi", "dxguid", "d3dcompiler", "shell32", "ole32")

    -- add src files
    add_files(
        "src/v2/**.cpp",
        "src/main.cpp",
        "src/render/WebView2HostWebRenderer.cpp",
        "src/render/Wv2SharedCompat.cpp",
        "src/composite/D3D12Compositor.cpp",
        "src/composite/EngineD3D12.cpp",
        "src/composite/ScaleformOverlayHook.cpp",
        "src/platform/WindowsPlatform.cpp",
        "src/runtime/DevViewFiles.cpp"
    )
    add_headerfiles("src/**.h")
    add_includedirs("src")
    add_includedirs("tools/webview2_shared")
    -- sdk/ holds the public single-header native API (OSFUI_API.h); 
    -- src/api includes it directly so the impl and the consumer copy share one ABI def.
    add_headerfiles("sdk/OSFUI_API.h", "sdk/OSFUI_JSON.h")
    add_includedirs("sdk")
    set_pcxxheader("src/pch.h")

    -- Ship authored plugin data next to the DLL. Built-in views are generated
    -- separately under build/frontend/views and copied by the hooks below.
    -- <install>/SFSE/Plugins/OSFUI/...
    add_installfiles("data/(OSFUI/**)", { prefixdir = "SFSE/Plugins" })
    -- the Papyrus API (authoring-settings.md "From Papyrus"): loose scripts
    -- at the Data root -- <install>/Scripts/OSFUI.pex (+ Source/OSFUI.psc)
    add_installfiles("data/(Scripts/**)")
    -- Build the ignored frontend artifact before native deployment (shared
    -- with before_install below — see tools/xmake/frontend_views.lua).
    before_build(function(target)
        import("frontend_views", { rootdir = path.join(os.projectdir(), "tools", "xmake") })
        frontend_views.build()
    end)
    -- Redeploy authored data + generated views to the mod folder on every build.
    -- The commonlib rule's after_build only runs "xmake install" when the DLL binary itself changed, so pure HTML/JS/JSON edits would otherwise never reach XSE_SF_MODS_PATH.
    after_build(function(target)
        if not (os.getenv("XSE_SF_MODS_PATH") or os.getenv("XSE_SF_GAME_PATH")) then
            return
        end
        import("core.project.depend")
        import("core.project.config")
        local datadir = path.join(os.projectdir(), "data", "OSFUI")
        local scriptsdir = path.join(os.projectdir(), "data", "Scripts")
        local viewsdir = path.join(os.projectdir(), "build", "frontend", "views")
        local files = os.files(path.join(os.projectdir(), "data", "**"))
        table.join2(files, os.files(path.join(viewsdir, "**")))
        depend.on_changed(function()
            local dstdir = path.join(target:installdir(), "SFSE", "Plugins")
            os.cp(datadir, dstdir)
            local deployed = path.join(dstdir, "OSFUI", "views")
            os.rm(path.join(deployed, "shared"))
            os.rm(path.join(deployed, "osfui"))
            os.cp(viewsdir, path.join(dstdir, "OSFUI"))
            -- Papyrus API: loose scripts at the Data root (mod folder root)
            os.cp(scriptsdir, target:installdir())
            cprint("${dim}deploying data/OSFUI + generated views + data/Scripts to %s ..", target:installdir())
        end, { files = files, values = files,
               dependfile = target:dependfile("osfui_data_deploy") })
        -- Out-of-process WebView2 host: ship the exe inside the plugin data
        -- dir (SFSE/Plugins/OSFUI/bin). The renderer mirrors it to a REAL
        -- path outside the MO2 VFS at runtime before broker-launching it.
        import("core.project.project")
        local host = project.target("osfui-webview2-host")
        if host and os.isfile(host:targetfile()) then
            local bindir = path.join(target:installdir(), "SFSE", "Plugins", "OSFUI", "bin")
            os.mkdir(bindir)
            os.cp(host:targetfile(), path.join(bindir, "osfui_webview2_host.exe"))
            cprint("${dim}deploying osfui_webview2_host.exe to %s ..", bindir)
        end
    end)

    -- xmake install is also used by the release packager. Install the
    -- production host explicitly; unlike the MO2 auto-deploy above, this path
    -- runs with XSE_SF_* unset and must not depend on an after-build side
    -- effect. ⚠ Do NOT fold this into before_build: `xmake install` does not
    -- run the build phase, and package.ps1 -SkipBuild relies on this hook.
    before_install(function(target)
        import("frontend_views", { rootdir = path.join(os.projectdir(), "tools", "xmake") })
        frontend_views.build()
    end)
    after_install(function(target)
        import("core.project.config")
        local viewsdir = path.join(os.projectdir(), "build", "frontend", "views")
        local datadir = path.join(target:installdir(), "SFSE", "Plugins", "OSFUI")
        os.rm(path.join(datadir, "views"))
        os.cp(viewsdir, datadir)
        import("core.project.project")
        local host = project.target("osfui-webview2-host")
        if not host or not os.isfile(host:targetfile()) then
            raise("OSFUI WebView2 host was not built; cannot install a runnable plugin")
        end
        local bindir = path.join(target:installdir(), "SFSE", "Plugins", "OSFUI", "bin")
        os.mkdir(bindir)
        os.cp(host:targetfile(), path.join(bindir, "osfui_webview2_host.exe"))
    end)

    add_syslinks(
        "d3d11", "dcomp", "windowsapp", "runtimeobject", "CoreMessaging",
        "shlwapi", "user32", "gdi32", "version",
        -- out-of-process host client (pipe ACL + Explorer/TaskScheduler broker)
        "oleaut32", "uuid", "comsuppw", "taskschd", "advapi32")
    -- Wv2SharedCompat.cpp compiles tools/webview2_shared through the pch.
    -- Host exe must exist before the data deploy below can package it.
    add_deps("osfui-webview2-host")
    -- NOTE: the plugin deliberately does NOT link the WebView2 SDK. Everything
    -- that touches the browser lives in osfui_webview2_host.exe; this DLL only
    -- speaks the pipe protocol. Keeping the proprietary loader out of the
    -- GPL-3.0 plugin is intentional — do not add it back for a convenience
    -- call. If you need runtime facts (version, availability), read them from
    -- the host's hello handshake.
