// build.schema.test.ts — validate every settings-schema JSON in the repo
// against the settings-schema JSON Schema we publish.
//
// This closes a real gap. docs/schema/settings-schema.schema.json is shipped
// to third-party authors as THE description of settings/<author>.<modname>.json
// and is wired into editors via each file's "$schema" key — but nothing in the
// build, in CI, or in the native runtime ever validated a file against it. The
// runtime parses leniently and skips what it does not understand, so a shipped
// file could drift out of conformance (or the schema could drift away from the
// files) and the only symptom would be a setting silently missing from the
// Mods surface. An author copying examples/settings-only/ as a starting point
// would then inherit the drift.
//
// Note the direction this test runs in: it validates the FILES against the
// SCHEMA, which means it fails when either side moves. That is intended — the
// two are a contract, and the shipped example is the reference implementation
// of it.

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import Ajv2020 from 'ajv/dist/2020';
import { REPO } from '../scripts/config.mjs';

// The schema declares draft 2020-12, which Ajv's default (draft-07) export
// cannot compile. See the same note in build.manifest.test.ts.
const schema = JSON.parse(
  readFileSync(join(REPO, 'docs', 'schema', 'settings-schema.schema.json'), 'utf8'),
);

// strict:false for the same reason as the manifest gate: the published schema
// carries human-facing annotations ("default", descriptions on branches) that
// Ajv strict mode reports as unknown keywords. Those are documentation, not
// validation rules.
const ajv = new Ajv2020({ strict: false, allErrors: true });
const validate = ajv.compile(schema);

// Every settings-schema file in the repo, found by grepping for the schema's
// own $schema URL and then hand-verifying each hit. Deliberately enumerated
// rather than globbed:
//   - a glob over the repo root also sweeps .claude/worktrees/**, which holds
//     other agents' in-flight copies of these same files. Validating those
//     would make this test's result depend on unrelated concurrent work.
//   - data/ is BUILD OUTPUT, but data/OSFUI/settings/osfui.json is not
//     generated by frontend/scripts — it is a hand-maintained shipped file
//     that happens to live under data/. It is read here, never written.
const files = [
  // The platform's own settings card. "osfui" is the one dotless id the schema
  // permits ("dotless ids are reserved for the platform").
  join(REPO, 'data', 'OSFUI', 'settings', 'osfui.json'),
  // The copy-me starter for third-party authors; exercises every v1 widget, so
  // it is the broadest single exercise of the schema in the repo.
  join(REPO, 'examples', 'settings-only', 'yourname.mymod.json'),
  // Papyrus native-API test fixture. Not shipped in releases, but it is a
  // settings-schema file the runtime loads during testing, and a fixture that
  // no longer conforms produces a confusing test failure two layers away.
  join(REPO, 'tests', 'papyrus', 'osfui.paptest.json'),
];

describe('shipped settings-schema JSON files', () => {
  it('all exist (a renamed/moved file must update this list, not vanish silently)', () => {
    expect(files.filter((f) => !existsSync(f))).toEqual([]);
  });

  it.each(files)('%s validates against settings-schema.schema.json', (file) => {
    const doc = JSON.parse(readFileSync(file, 'utf8'));
    const ok = validate(doc);
    // Print Ajv's messages on failure; a bare boolean assertion here is
    // undebuggable against a 15KB schema.
    expect(ajv.errorsText(validate.errors, { separator: '\n' })).toBe('No errors');
    expect(ok).toBe(true);
  });

  it.each(files)('%s has an "id" matching its filename stem', (file) => {
    // The schema documents this rule ("Must equal the filename stem, so the
    // file is settings/<author>.<modname>.json") but cannot enforce it —
    // JSON Schema has no view of the filename. The loader keys mods by the id
    // INSIDE the file, so a mismatch means the settings land under a mod id
    // that no other file, translation catalog, or Papyrus call references.
    const doc = JSON.parse(readFileSync(file, 'utf8')) as { id?: unknown };
    const stem = file.split(/[\\/]/).pop()!.replace(/\.json$/, '');
    expect(doc.id).toBe(stem);
  });
});
