// No browser/game dependency: exercise the shipped facade against v2 envelopes.
const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('src/Compat/V1/web/osfui.js', 'utf8');
test('legacy ready, sends, typed replies, errors and gamepad events use v2 transport', async () => {
  const sent = [];
  const window = { osfui: { postMessage: text => sent.push(JSON.parse(text)) } };
  vm.runInNewContext(source, { window, console, setTimeout, clearTimeout });
  const api = window.osfui;
  const receive = message => api.onMessage(JSON.stringify(message));
  assert.equal(sent[0].name, 'osfui.hello');
  assert.equal(sent[0].kind, 'send');
  receive({ kind: 'ready', payload: { version: '2.0.0' } });
  assert.equal((await api.ready).version, '2.0.0');
  api.emit('starcade.arcade.state.get');
  assert.equal(sent.at(-1).payload.command, 'starcade.arcade.state.get');
  let received;
  const off = api.on('ui.gamepad', (payload, envelope) => received = [payload, envelope]);
  receive({ kind: 'event', name: 'ui.gamepad', payload: { kind: 'button' } });
  assert.equal(received[0].kind, 'button');
  assert.equal(received[1].type, 'ui.gamepad');
  off();
  received = undefined;
  receive({ kind: 'event', name: 'ui.gamepad', payload: {} });
  assert.equal(received, undefined);
  const reply = api.call('GetPluginsRequest', {});
  const request = sent.at(-1);
  assert.equal(request.kind, 'request');
  receive({ kind: 'reply', id: request.id, payload: { __osfuiV1Reply: true, type: 'plugins', payload: { count: 3 } } });
  assert.equal((await reply).count, 3);
  const envelope = api.request('GetFormsRequest');
  receive({ kind: 'reply', id: sent.at(-1).id, payload: { __osfuiV1Reply: true, type: 'forms', payload: [] } });
  assert.equal((await envelope).type, 'forms');
  const failure = api.call('GetFormsRequest');
  receive({ kind: 'error', id: sent.at(-1).id, payload: { code: 'rejected', message: 'unavailable' } });
  await assert.rejects(failure, error => error.code === 'rejected');
});
