#include "World/WorldViewPolicy.h"
#include <cassert>
#include <vector>

int main()
{
	using namespace OSFUI;
	using namespace OSFUI::WorldAssets;
	// These expected keys were observed in TextureDB and renderer publication
	// in the .244 QASmoke fixture, not generated by this implementation.
	assert((KeyForPath("textures/OSFUIWorldTest/board0.dds") == Key{ 0xadf9fc9a, 0x00736464, 0x07e6c45a }));
	assert((KeyForPath("textures/OSFUIWorldTest/board3.dds") == Key{ 0x34f0ad20, 0x00736464, 0x07e6c45a }));
	assert(KeyForPath("TEXTURES/OSFUIWorldTest/board0.dds") == KeyForPath("textures/OSFUIWorldTest/board0.dds"));
	std::vector<ViewManifest> views;
	for (int i = 0; i < 64; ++i) {
		ViewManifest view;
		view.id = "stocks/board-" + std::to_string(i);
		view.kind = ViewKind::World;
		view.texture = "textures/example/board-" + std::to_string(i) + ".dds";
		view.width = view.height = 1000;
		views.push_back(view);
	}
	for (const auto& view : views) assert(!FindWorldBindingConflict(view, views, false));
	views[63].id = "arcade/cabinet";
	views[63].texture = views[0].texture;
	assert(FindWorldBindingConflict(views[0], views, false) == &views[63]);
	assert(FindWorldBindingConflict(views[63], views, false) == &views[0]);
	std::ranges::reverse(views);
	assert(FindWorldBindingConflict(views[0], views, false) == &views[63]);
	views[0].debugOnly = true;
	assert(!IsEligibleWorldView(views[0], false));
	assert(!FindWorldBindingConflict(views[63], views, false));
	assert(FindWorldBindingConflict(views[63], views, true) == &views[0]);
	views[0].kind = ViewKind::Hud;
	assert(!FindWorldBindingConflict(views[63], views, true));
	views[0].kind = ViewKind::World;
	views[0].debugOnly = false;
	views[0].id = "STOCKS/BOARD-0";
	views[0].texture = "textures/another/independent.dds";
	assert(FindWorldBindingConflict(views[63], views, false) == &views[0]);
}
