set_project("OSF UI Schema Checks")
set_languages("c++23")
add_requires("nlohmann_json")
target("settings-schema-tests")
    set_kind("binary")
    add_files("settings_schema_tests.cpp", "key_stubs.cpp", "../../lib/osf-settings/src/Settings/SettingsSchemaJson.cpp",
        "../../lib/osf-settings/src/Settings/SettingsSchema.cpp", "../../lib/osf-settings/src/Settings/SettingsJson.cpp")
    add_includedirs("../../lib/osf-settings/src", "../native/stubs")
    add_packages("nlohmann_json")
    set_rundir(os.scriptdir())
